### ISSUE TITLE
Argument verification

### ISSUE THREAD

**Issue by chengsoonong** [chengsoonong/acton#22]
I am imagining some syntactic sugar that could be a decorator or one line at the beginning of each function. Basically type checking, and disallowing certain combinations of arguments.

I am not sure whether there is already an existing package that does this.

**Comment by MatthewJA** [comment]
There's definitely libraries for type-checking based on function annotations (and since I'm already using function annotations, that'd be straightforward to plug in). I'm not sure of a use case for a decorator that disallows certain combinations &mdash; specifically, I am not sure what combinations would be sufficiently generic to warrant a decorator instead of just doing the verification inline.

**Comment by chengsoonong** [comment]
Shall we close this as won't fix?

**Comment by MatthewJA** [comment]
Yeah.
